### ISSUE TITLE
how to keep the application running

### ISSUE THREAD

**Issue by saveriogzz** [goeh/weather-collector#7]
Hi @goeh !
Some nice findings: with a MySQL server running on a Docker container and it has wrote all the values into it!
During the run, it ran for nearly 11 minutes and it stopped after that.

My (very important) question is: how can I run the application undefinitely?

Cheers

**Comment by goeh** [comment]
Great news!
The application is designed to be started as a cron job. For example every 10 minutes. Not to be run continuously.
The first time you run the application it downloads all data from the weather station (takes 10+ minutes). Next time it knows where to continue, and only downloads new data since last run.
To run continuously, you have to implement some kind internal scheduler. The weather station does not send events, so you have to poll the station at some regular interval. I found cron to be a simple solution for that.

**Comment by goeh** [comment]
You can have the Docker container run cron at startup. That's the easiest solution. I can find some example cron Dockefile if you're interested.

**Comment by saveriogzz** [comment]
thanks @goeh !
So you run that every x minutes by using cron?

**Comment by goeh** [comment]
Yes, I have a cron job that runs every 10 minutes. It's been like that since 2008. I have over 20 M records in the database :)

**Comment by goeh** [comment]
The cron implementations differ depending on distro. What base image are you using in your Dockerfile?

**Comment by saveriogzz** [comment]
At the moment I am using Docker just to run the MySQL database! Sorry, I'm a  bit confused: are you using Docker to run the application itself?

**Comment by goeh** [comment]
No I'm not. I'm running a simple cron job on the Raspberry Pi (Raspbian). I thought you wanted to run Docker ;-)

**Comment by saveriogzz** [comment]
oh yes! now I get what you mean!
Yes I would like to package the different services (database and java app) into some docker containers but first I will focus into the streaming part (I hope to finish before Thursday)
